# Generated by Django 4.0.6 on 2022-07-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars_data',
            name='status',
        ),
    ]
