# Generated by Django 4.0.6 on 2022-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_cars_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_data',
            name='types',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
